[2025-03-10T11:47:27.292+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T11:47:27.296+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_processing_pipeline.filtering.filter_by_location manual__2025-03-10T10:47:20.464817+00:00 [queued]>
[2025-03-10T11:47:27.298+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_processing_pipeline.filtering.filter_by_location manual__2025-03-10T10:47:20.464817+00:00 [queued]>
[2025-03-10T11:47:27.298+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-10T11:47:27.302+0100] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): filtering.filter_by_location> on 2025-03-10 10:47:20.464817+00:00
[2025-03-10T11:47:27.304+0100] {standard_task_runner.py:72} INFO - Started process 21661 to run task
[2025-03-10T11:47:27.307+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transaction_processing_pipeline', 'filtering.filter_by_location', 'manual__2025-03-10T10:47:20.464817+00:00', '--job-id', '74', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/77/x0zgg14j4mv45pmn3j9n0_ym0000gn/T/tmp9sexrfa7']
[2025-03-10T11:47:27.308+0100] {standard_task_runner.py:105} INFO - Job 74: Subtask filtering.filter_by_location
[2025-03-10T11:47:27.320+0100] {task_command.py:467} INFO - Running <TaskInstance: transaction_processing_pipeline.filtering.filter_by_location manual__2025-03-10T10:47:20.464817+00:00 [running]> on host mac.lan
[2025-03-10T11:47:27.340+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kounta' AIRFLOW_CTX_DAG_ID='transaction_processing_pipeline' AIRFLOW_CTX_TASK_ID='filtering.filter_by_location' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T10:47:20.464817+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T10:47:20.464817+00:00'
[2025-03-10T11:47:27.340+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T11:47:27.341+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T11:47:27.341+0100] {logging_mixin.py:190} INFO - Current task name:filtering.filter_by_location state:running start_date:2025-03-10 10:47:27.296235+00:00
[2025-03-10T11:47:27.341+0100] {logging_mixin.py:190} INFO - Dag name:transaction_processing_pipeline and current dag run status:running
[2025-03-10T11:47:27.341+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T11:47:27.348+0100] {logging_mixin.py:190} WARNING - /Users/salematoukounta/airflow/dags/etl_dag.py:55 FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
[2025-03-10T11:47:27.361+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/dags/etl_dag.py", line 63, in filter_by_location
    location_df.to_csv(OUTPUT_PATH.format(location), index=False)
AttributeError: 'PosixPath' object has no attribute 'format'
[2025-03-10T11:47:27.364+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T11:47:27.364+0100] {logging_mixin.py:190} INFO - Task start:2025-03-10 10:47:27.296235+00:00 end:2025-03-10 10:47:27.364474+00:00 duration:0.068239
[2025-03-10T11:47:27.364+0100] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): filtering.filter_by_location> dag:<DAG: transaction_processing_pipeline> dagrun:<DagRun transaction_processing_pipeline @ 2025-03-10 10:47:20.464817+00:00: manual__2025-03-10T10:47:20.464817+00:00, state:running, queued_at: 2025-03-10 10:47:20.468620+00:00. externally triggered: True>
[2025-03-10T11:47:27.365+0100] {logging_mixin.py:190} INFO - Failure caused by 'PosixPath' object has no attribute 'format'
[2025-03-10T11:47:27.365+0100] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transaction_processing_pipeline, task_id=filtering.filter_by_location, run_id=manual__2025-03-10T10:47:20.464817+00:00, execution_date=20250310T104720, start_date=20250310T104727, end_date=20250310T104727
[2025-03-10T11:47:27.369+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T11:47:27.369+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 74 for task filtering.filter_by_location ('PosixPath' object has no attribute 'format'; 21661)
Traceback (most recent call last):
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/dags/etl_dag.py", line 63, in filter_by_location
    location_df.to_csv(OUTPUT_PATH.format(location), index=False)
AttributeError: 'PosixPath' object has no attribute 'format'
[2025-03-10T11:47:27.403+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T11:47:27.408+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T11:47:27.408+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
