[2025-03-10T11:21:40.110+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-10T11:21:40.114+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: transaction_processing_pipeline.determine_branch manual__2025-03-10T10:21:35.344748+00:00 [queued]>
[2025-03-10T11:21:40.116+0100] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: transaction_processing_pipeline.determine_branch manual__2025-03-10T10:21:35.344748+00:00 [queued]>
[2025-03-10T11:21:40.116+0100] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-10T11:21:40.120+0100] {taskinstance.py:2890} INFO - Executing <Task(BranchPythonOperator): determine_branch> on 2025-03-10 10:21:35.344748+00:00
[2025-03-10T11:21:40.122+0100] {standard_task_runner.py:72} INFO - Started process 19150 to run task
[2025-03-10T11:21:40.124+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'transaction_processing_pipeline', 'determine_branch', 'manual__2025-03-10T10:21:35.344748+00:00', '--job-id', '48', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/var/folders/77/x0zgg14j4mv45pmn3j9n0_ym0000gn/T/tmpddr0gpk3']
[2025-03-10T11:21:40.125+0100] {standard_task_runner.py:105} INFO - Job 48: Subtask determine_branch
[2025-03-10T11:21:40.137+0100] {task_command.py:467} INFO - Running <TaskInstance: transaction_processing_pipeline.determine_branch manual__2025-03-10T10:21:35.344748+00:00 [running]> on host mac.lan
[2025-03-10T11:21:40.153+0100] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kounta' AIRFLOW_CTX_DAG_ID='transaction_processing_pipeline' AIRFLOW_CTX_TASK_ID='determine_branch' AIRFLOW_CTX_EXECUTION_DATE='2025-03-10T10:21:35.344748+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-10T10:21:35.344748+00:00'
[2025-03-10T11:21:40.154+0100] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-10T11:21:40.154+0100] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-10T11:21:40.154+0100] {logging_mixin.py:190} INFO - Current task name:determine_branch state:running start_date:2025-03-10 10:21:40.114646+00:00
[2025-03-10T11:21:40.154+0100] {logging_mixin.py:190} INFO - Dag name:transaction_processing_pipeline and current dag run status:running
[2025-03-10T11:21:40.154+0100] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-10T11:21:40.155+0100] {baseoperator.py:423} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-03-10T11:21:40.156+0100] {logging_mixin.py:190} INFO - Branching action: None
[2025-03-10T11:21:40.156+0100] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/dags/etl_dag.py", line 47, in determine_branch
    if transform_action.startswith('filter'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2025-03-10T11:21:40.160+0100] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-10T11:21:40.160+0100] {logging_mixin.py:190} INFO - Task start:2025-03-10 10:21:40.114646+00:00 end:2025-03-10 10:21:40.159894+00:00 duration:0.045248
[2025-03-10T11:21:40.160+0100] {logging_mixin.py:190} INFO - Task:<Task(BranchPythonOperator): determine_branch> dag:<DAG: transaction_processing_pipeline> dagrun:<DagRun transaction_processing_pipeline @ 2025-03-10 10:21:35.344748+00:00: manual__2025-03-10T10:21:35.344748+00:00, state:running, queued_at: 2025-03-10 10:21:35.351890+00:00. externally triggered: True>
[2025-03-10T11:21:40.160+0100] {logging_mixin.py:190} INFO - Failure caused by 'NoneType' object has no attribute 'startswith'
[2025-03-10T11:21:40.160+0100] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=transaction_processing_pipeline, task_id=determine_branch, run_id=manual__2025-03-10T10:21:35.344748+00:00, execution_date=20250310T102135, start_date=20250310T102140, end_date=20250310T102140
[2025-03-10T11:21:40.165+0100] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-10T11:21:40.165+0100] {standard_task_runner.py:124} ERROR - Failed to execute job 48 for task determine_branch ('NoneType' object has no attribute 'startswith'; 19150)
Traceback (most recent call last):
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 274, in execute
    return self.do_branch(context, super().execute(context))
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/Users/salematoukounta/airflow/airflow_env/lib/python3.9/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/Users/salematoukounta/airflow/dags/etl_dag.py", line 47, in determine_branch
    if transform_action.startswith('filter'):
AttributeError: 'NoneType' object has no attribute 'startswith'
[2025-03-10T11:21:40.178+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-10T11:21:40.185+0100] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-10T11:21:40.186+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
